### ISSUE TITLE
Add a hillshade function

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/xdem#102]
After discussion with @erikmannerfelt, we agreed to include the hillshade function of [earthpy](https://earthpy.readthedocs.io/en/latest/gallery_vignettes/plot_dem_hillshade.html) to xdem.
This seem to show different results than gdaldem hillshade by default, but can be solved by a zFactor of ~10-50.

Without scaling factor
https://files.slack.com/files-pri/T01D6EMSU0J-F01V0U7FWAH/figure_1.png

With scaling factor 50
https://files.slack.com/files-pri/T01D6EMSU0J-F01V47N24JX/figure_1.png

**Comment by erikmannerfelt** [comment]
To be clear, we discussed that the earthpy function could use some improvements, and we therefore decided to make our own. Other would be intellectual theft, right!?

**Comment by erikmannerfelt** [comment]
Added in #104
