### ISSUE TITLE
volume.interpolate_hypsometric_bins does not return proper pandas dataframe

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/xdem#105]
When running `volume.interpolate_hypsometric_bins`, the output is different from the input. In particular, it does not contain the attribute "value" which can cause issues when the output is passed to other xdem.volume functions like `calculate_hypsometry_area`.
The output should be consistent.

**Comment by adehecq** [comment]
This change will impact the scipy.interpolate.interp1d calls in hypsometric_interpolation and local_hyspometric_interpolation -> these lines must be updated.

**Comment by erikmannerfelt** [comment]
I'm on it!
