### ISSUE TITLE
Improve Nuth and Kääb 2011 implementation by stopping when error stops improving

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/xdem#124]
Currently, there's a pretty lazy threshold system where if the NMAD drops below 0.05, it will end prematurely:
https://github.com/GlacioHack/xdem/blob/b22b4b5f65bd8f8ca2daa601d1f27bbc74cef773/xdem/coreg.py#L1127
It would be much better to stop when the NMAD stops improving instead, because most of the time, the NMAD will never reach 0.05. This could be done either with a simple check "check that the NMAD was better than last time" or better, check with the last X errors "check that the NMAD improved compared to any of the last X iterations". The latter is preferable as it is less likely to stop in local minima.

**Comment by adehecq** [comment]
Solved by #135
