### ISSUE TITLE
Remove richdem as dependency

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/xdem#127]
No function (apart from some conversion functions, which are in turn not used) uses richdem. I propose to remove it as a dependency for three reasons:

1. It is a bit complicated to install on Windows
2. It is not on conda-forge. Since we want to get there eventually, I think it's good that we revise all non-conda-forge dependencies.
3. It's not really used!

**Comment by rhugonnet** [comment]
+1, especially given #147 coming right up (except if we want it in the test scripts? not sure we do...)
