### ISSUE TITLE
`xdem` NuthKaab documentation example is wrong

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/xdem#128]
Something is very wrong with the `NuthKaab` example figure!

https://xdem.readthedocs.io/en/latest/coregistration.html

**Comment by adehecq** [comment]
While looking at this, note that the link to the associated paper is wrong. It points to https://xdem.readthedocs.io/en/latest/https:/doi.org/10.5194/tc-5-271-2011 instead of https:/doi.org/10.5194/tc-5-271-2011.
