### ISSUE TITLE
Allow point clouds for `Coreg`

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/xdem#134]
A suggestion for the memory problem.

A DEM is often quite large, so how does one do coregistration on just a subsample?

* A geoutils function to "read N pixels as a X/Y/Z point cloud"
* Allow X/Y/Z point clouds to be used for the `Coreg` class. They could be of shape (rows, 3), and all with shape[1] == 3 and len(shape) == 2 could be parsed as point clouds.

**Comment by rhugonnet** [comment]
Typically, I randomly subsample the elevation differences with N samples, as in `sptats.py`:
```python
def random_subset(dh: np.ndarray, coords: np.ndarray, nsamp: int):
    """
    Subsampling of elevation differences with random coordinates

    :param dh: elevation differences
    :param coords: coordinates
    :param nsamp: number of sammples for subsampling

    :return: subsets of dh and coords
    """
    if len(coords) > nsamp:
        subset = np.random.choice(len(coords), nsamp, replace=False)
        coords_sub = coords[subset]
        dh_sub = dh[subset]
    else:
        coords_sub = coords
        dh_sub = dh

    return dh_sub, coords_sub```
What would be the benefit of using point clouds to deal with this issue? I'm not too familiar with those!

**Comment by erikmannerfelt** [comment]
@rhugonnet, that's a very nice approach of subsampling a DEM that is already in memory! The potential issue we try to tackle is when one does not want to load the entire DEM, or the reference is not actually a DEM. Some use-cases of allowing point clouds, plus loading subsets of DEMs as point clouds are:

1. Coregistration can easily be done on arbitrarily large DEMs
2. Reference data such as ICESat which are in point-cloud format could be used as reference points.
3. If the data to be aligned are not DEMs but e.g. photogrammetry-derived point clouds or digitized contour lines, they could be used without first gridding them.

**Comment by rhugonnet** [comment]
Partially introduced by #346, need to refine and allow out-of-memory point sampling. Maybe we can inspire ourselves from what is done in https://github.com/ICESat2-SlideRule/sliderule.
