### ISSUE TITLE
Simplify Raster.reproject

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/xdem#146]
We could use the functionality in rasterio.warp.calculate_default_transform to make the calculation of the transform easier in Raster.reproject (I should have seen that earlier...):
https://rasterio.readthedocs.io/en/latest/api/rasterio.warp.html#rasterio.warp.calculate_default_transform

**Comment by erikmannerfelt** [comment]
Was this issue meant for GeoUtils, @adehecq?

**Comment by adehecq** [comment]
Absolutely, I'll move this!
