### ISSUE TITLE
Deprecate `xdem.spatial_tools.subtract_rasters`

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/xdem#163]
This was a very useful function back in the days! With the addition of @adehecq's operators on Rasters, however, it is more or less redundant now.

## How to subtract a raster
Pre-May (when it was needed):
```python
dem2_reproj = dem2.reproject(dem1, resampling="...")

ddem = xdem.DEM.from_array(dem1.data - dem2_reproj.data, transform=dem1.transform, crs=dem1.crs)
```
With the (now redundant function):
```python
ddem = xdem.spatial_tools.subtract_rasters(dem1, dem2, resampling="...")
```
Today:
```python
ddem = dem1 - dem2.reproject(dem1, resampling="...")
```

There are fewer lines when not using my function and instead @adehecq's operators. Therefore, I would consider `xdem.spatial_tools.subtract_rasters` redundant.

Should we remove it, @adehecq @rhugonnet ?

**Comment by adehecq** [comment]
Agreed! I just thought about it a few days ago when I was reading the documentation...
