### ISSUE TITLE
Blockwise coregistration example fails with large gaps

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/xdem#189]
At line https://github.com/GlacioHack/xdem/blob/71aa08516ea19f9b0b1967a8100b54467c787ee0/examples/plot_blockwise_coreg.py#L87
the script will fail if in the example the DEM is rotated after reprojection e.g. with
```
reference_dem = reference_dem.reproject(dst_crs='EPSG:3413', dst_res=reference_dem.res, resampling='bilinear')
dem_to_be_aligned = dem_to_be_aligned.reproject(dst_ref=reference_dem, resampling='bilinear')
```
The error is 
> <ipython-input-5-d8980d4be069> in <module>
> ----> 1 for _, row in blockwise.stats().iterrows():
>       2     plt.annotate(round(row["z_off"], 1), (row["center_x"], row["center_y"]), ha
>       3 ="center")
> 
> ~/development/GlacioHack/xdem/xdem/coreg.py in stats(self)
>    1783                     "y_off": points[i, 1, 1] - points[i, 1, 0],
>    1784                     "z_off": points[i, 2, 1] - points[i, 2, 0],
> -> 1785                     "inlier_count": chunk_meta[i]["inlier_count"],
>    1786                     "nmad": chunk_meta[i]["nmad"],
>    1787                     "median": chunk_meta[i]["median"]
> 
> KeyError: 0
> 
This is due to the fact that statistics do not exist for empty chunks. Hence the method self.stats should be updated accordingly.

Somewhat related, if commenting out the problematic line, the estimated vertical bias for that case does not look very convincing... :thinking: 
![Figure_1](https://user-images.githubusercontent.com/3285905/125102052-2c434d80-e0db-11eb-9a95-7b75f8eaf70e.png)

**Comment by erikmannerfelt** [comment]
Thanks for finding this, @adehecq! I managed to reproduce the error with a single line haha in  `tests/test_coreg.py::TestCoregClass::test_blockwise_coreg_large_gaps` by adding:

```python
stats = blockwise.stats()
```

I'll get on it.
