### ISSUE TITLE
Release 0.0.5

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/xdem#194]
0.0.4 is now 1½ months old. Let's release a new version already!

## Changelog
- Added normalized hypsometric interpolation functions
- Added N-dimensional binning function (for biases, non-stationarity quantification etc..
- Added subsampling function
- Added blockwise coregistration class.
- Added N-dimensional linear interpolation functions.
- Improved Raster/ndarray interchangeability
- Performance enhancements.
- Lots of bugfixes.

Have I missed anything, @adehecq @rhugonnet ?

**Comment by adehecq** [comment]
Seems quite exhaustive!

**Comment by rhugonnet** [comment]
@erikmannerfelt We can close this, I think?

**Comment by adehecq** [comment]
Done on 17 Aug.
