### ISSUE TITLE
Blockwise coregistration apply method does not take nodata properly into account

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/xdem#195]
When the DEM is resampled during the blockwise coregistration, if nodata value exist, they will "leak" around the gaps.
A way to visualize it is to run the plot_blockwise_coreg.py example script and at [L 76](https://github.com/GlacioHack/xdem/blob/a5036f30b4ae01ac85791d423d13f57a546bdd9c/examples/plot_blockwise_coreg.py#L76)* to create an artificial gap in the DEM, e.g. with:
```
dem_to_be_aligned.data[0, 450:500, 450:500] = -9999
dem_to_be_aligned.set_ndv(-9999)
```
The nodata "leak" shows up on the upper edge of the gap. See attached figure.
The issue is that the nodata values are used in the resampling, so the "leaked" values do not match the nodata value and can be extremely difficult to filter out.
![Figure_2](https://user-images.githubusercontent.com/3285905/126666633-acec05fc-c0e0-4895-9e3c-f7cfc7ad7388.png)

I just checked and apparently, the issue shows up when running the same example with the Nuth & Kaab coregistration instead, but to a lesser extent.
![Figure_1](https://user-images.githubusercontent.com/3285905/126667141-7fdeea23-c283-4e63-b0b9-066d092516a1.png)

* **Note:** the script must be interrupted at that line. For some reason, if the entire script is run and then L 75-77 are re-run, without any change, they fail with the following error. Maybe one of the variables is being modified later in the script?
> LinAlgError: Matrix is singular.

**Comment by adehecq** [comment]
Apparently, something funky is going on with the NaN mask. It should simply be translated and not warped like this.
![Figure_3](https://user-images.githubusercontent.com/3285905/126673579-0144167b-dd30-47dc-b3cd-d39be2e4d887.png)

This is due to the lines [here](https://github.com/GlacioHack/xdem/blob/a5036f30b4ae01ac85791d423d13f57a546bdd9c/xdem/coreg.py#L1442). I'm not sure why the filling is needed here, as in my test case, tranformed_points does not contain any gap. Any idea @erikmannerfelt ?
Anyway, the issue is fixed by replacing those lines with:
```
x_inds = transformed_points[:, :, 0].copy()
y_inds = transformed_points[:, :, 1].copy()
```
But I'm not sure if that won't break other things? This is another argument towards #140 !

**Comment by adehecq** [comment]
Actually, it solves the issue for NuthKaab, but not for blockwise. For that one, apparently the dilate_mask option has no effect...
And it's impossible to stop the execution in the middle to check some results due to the asynchronous run.

**Comment by adehecq** [comment]
Weirdly, in blockwise, the function apply_matrix is run during coreg.fit, instead of coreg.apply (as can be seen by printing out on screen during that function). I really don't understand what is going on...

**Comment by adehecq** [comment]
I'm giving up. @erikmannerfelt I hope you can check that when you come back.

**Comment by erikmannerfelt** [comment]
Am I right to assume that the problem only occurs when Rasters are supplied, and not when numpy arrays are given to the Coreg functions?

I've identified the problem and I have a fix for Rasters. Now I just need to know if you found another problem or if we are talking about the same thing

**Comment by adehecq** [comment]
> Am I right to assume that the problem only occurs when Rasters are supplied, and not when numpy arrays are given to the Coreg functions?
> 
> I've identified the problem and I have a fix for Rasters. Now I just need to know if you found another problem or if we are talking about the same thing

No, if you check the example script, a numpy array is passed, not a Raster. This issue actually occurred before PR #175.

**Comment by erikmannerfelt** [comment]
Okay, thanks. I'll see if my fixes solves it.

**Comment by erikmannerfelt** [comment]
It seems to work! I'll mention it in the PR.
![image](https://user-images.githubusercontent.com/33550973/127630475-f5630d7c-b9c0-4a47-837c-cb674c6e0d68.png)

**Comment by adehecq** [comment]
Fantastic!
