### ISSUE TITLE
Bugs and suggestions of improvements in spatialstats

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/xdem#252]
While I was testing the different examples related to the spatialstats.py module on the documentation, I found a few issues and maybe some ways from improvement:

- [x] Functions `plot_1d_binning` and `plot_2d_binning` display the NMAD (in many examples the default). But this may not be calculated, and the functions plot NaNs instead of raising an error. The issue is at [this line](https://github.com/GlacioHack/xdem/blob/674c94785df07097da1aeedbdb60ae87392a6636/xdem/spatialstats.py#L1462), where a blank "nmad" (or whatever `statistic_name` is) column is created.
One way to test is to run the `plot_standardization.py` example and trying plotting the histograms, e.g.:
```
xdem.spatialstats.plot_1d_binning(df, "slope", "nmad", "Slope (degrees)", "NMAD of dh (m)")
plt.show()

xdem.spatialstats.plot_2d_binning(df, "slope", "maxc", "nmad")
plt.show()
```
It works fine if "nanstd" is used instead of "nmad". So this is more about catching a misuse (encouraged by most examples) than an actual bug.

- [x] related to the previous point, to avoid confusion with the other example (e.g. `plot_nonstationary_error.py`, one could calculate the nmad instead/on top of the nanstd.

- [x] the doctstring of `fit_sum_model_variogram` could be a bit more detailed, e.g.:
   - ":param list_model: list of K variogram models to sum for the fit: from short-range to long-ranges" -> what are "variogram models", it's unclear what should be passed (from the doc examples, "sph" is an option. This should be clearly stated what the options are here.
   - ":param empirical_variogram: empirical variogram" -> specify "as returned by sample_empirical_variogram"
   - ":return: modelled variogram function, coefficients" -> it should say which coefficients and in which order, so that one can figure out what are the sills and ranges
   
- [x] in the docstring of `exact_neff_sphsum_circular`, also detail what units are expected for the inputs (they should at least all be the same, but most likely should be in m or m2).

- [x] related to the previous point, in the example `plot_standardization.py`, Neff is calculated using the following area attribute `svendsen_shp.ds['Shape_Area'].values`. This example can be a bit more difficult to translate to another dataset if that particular attribute is not available. Maybe in that example, we could calculate the area using geopandas functionalities, e.g. `glacier_outlines.ds.area`. In my case, I was tricked because I used the RGI "Area" attribute, which is in km2 so not the right unit... 

I may add more bullet points in the future as I play with the examples.
Apart from these minor issues, the examples are great !

**Comment by adehecq** [comment]
- [ ] The default arguments in `sample_empirical_variogram` (see [here](https://github.com/GlacioHack/xdem/blob/674c94785df07097da1aeedbdb60ae87392a6636/xdem/spatialstats.py#L554)) are not appropriate:
    - `runs` is not set by default, and I think it is set later by skgstat at a huge value (2436 in my test) as opposed to 30 as in the doc examples, so this will run forever
    - `subsample` is set to 10000, which is also huge for the 'cdist_equidistant' sampling method if I'm not mistaken
    All in all, if running the method with the default arguments will run forever. On top of that, the link between the different arguments is unclear. `runs` is not explained since it's a kwarg, and if I understand correctly, the actual number of samples will be subsample * runs, not subsample as would be intuitive.

**Comment by rhugonnet** [comment]
Oh yes this last one is tricky! It's good if we can an "empirical" way to optimize the default number of `runs` and `subsamples` depending the Raster size. But it's not easy to determine!

**Comment by adehecq** [comment]
- [ ] [spatialstats.neff_circ](https://github.com/GlacioHack/xdem/blob/674c94785df07097da1aeedbdb60ae87392a6636/xdem/spatialstats.py#L882) fails with a weird error if the variogram names are not as expected, e.g. "Sphere" instead of "Sph". There should be a simple check for this.
