### ISSUE TITLE
Elaborate on the `bins` column in empirically sampled variograms

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/xdem#253]
I had a journey trying to figure out if the `bins` column represented the upper bound or the centrepoint of the bin!

Because of this line, I made the assumption that this is in fact decided by skgstat (since no default argument is given):
https://github.com/GlacioHack/xdem/blob/674c94785df07097da1aeedbdb60ae87392a6636/xdem/spatialstats.py#L467

And skgstat in turn (currently) has the default that it's the upper bound:
https://github.com/mmaelicke/scikit-gstat/blob/69074feefb3759ba75c4ee91a5a9fced8d872801/skgstat/Variogram.py#L1790

This should be mentioned in the docstring of `xdem.spatial_stats.sample_empirical_variogram()` and anywhere else that it might be relevant!

**Comment by erikmannerfelt** [comment]
Also, regarding this, perhaps it's best to provide the `bin_center=False` argument to `V.get_empirical()`. Not that I suspect it may change, but that would make potential debugging easier in the future, plus we would "be notified" (i.e. failed tests) if skgstat changes behaviour.

**Comment by rhugonnet** [comment]
Good idea! Yes, everything is decided by `skgstat`! We probably don't want to duplicate its documentation, but it should be made clearer what is the default for the most common input and output variables :)
