### ISSUE TITLE
Create a one-liner for DEM coregistration

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/xdem#257]
Currently, the easiest way to run DEM coregistration is to follow the example [here](https://github.com/GlacioHack/xdem/blob/main/examples/plot_nuth_kaab.py). This is several lines long, including reading files, reprojecting, creating mask, running coreg.fit and apply, saving to disk...
Ideally this could be done in a single function with some default parameters, as done for [RAGMAC](https://github.com/adehecq/ragmac_xdem/blob/master/ragmac_xdem/dem_postprocessing.py#L325 ).

**Comment by erikmannerfelt** [comment]
@adehecq, is this solved now?

**Comment by rhugonnet** [comment]
Essentially, but there was still a list of TODOs in #267. Maybe it can be moved to a new issue "Refine one-liner for DEM coregistration"?

**Comment by rhugonnet** [comment]
Actually an issue for refining that PR is opened: #324, closing!
