### ISSUE TITLE
Clean coreg.py

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/xdem#266]
There seem to be several unused functions in coreg.py, e.g.:
- get_terrainattr
- rio_to_rda
- mask_as_array -> used only once in ddem.py...

It would be good to remove those if they are indeed not used anymore. @rhugonnet and @erikmannerfelt, if you give me the go, I can delete/move them as part of my next PR.

**Comment by rhugonnet** [comment]
Agreed! The first two functions, I moved and updated into `terrain.py` in #227, they are now used there.

**Comment by adehecq** [comment]
Sorry, I did not realize that I did not look at the latest commit and the richdem related functions had already been moved !

**Comment by rhugonnet** [comment]
This is closed by #530
