### ISSUE TITLE
DEM difference raster can be imported using xdem.dDEM()?

### ISSUE THREAD

**Issue by arindan** [GlacioHack/xdem#274]
Hi everyone,

I have been playing with the xDEM. I was trying to import/open my DEM difference raster (differenced in other platform) as xdem.dDEM (ddem), but I am not successful. Below is the code and error I got, if anyone of you can have quick look:

**Code line**
```
ddem = xdem.dDEM('zanskar_dh_masked_abs100m_removed.tif', start_time= '2000-02-15', end_time= '2020-09-30')
```

**Error**
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 ddem = xdem.dDEM('zanskar_dh_masked_abs100m_removed.tif', start_time= '2000-02-15', end_time= '2020-09-30')

File ~/anaconda3/envs/xdem/lib/python3.9/site-packages/xdem/ddem.py:32, in dDEM.__init__(self, raster, start_time, end_time, error)
     20 """
     21 Create a dDEM object from a Raster.
     22 
   (...)
     28 :returns: A new dDEM instance.
     29 """
     30 # super().__init__(raster)
---> 32 self.__dict__ = raster.__dict__
     33 self.start_time = start_time
     34 self.end_time = end_time

AttributeError: 'str' object has no attribute '__dict__'
```

Any guess what could solve this issue? Or how I can import my DEM difference raster as dDEM using xDEM? 
Note: I don't want to difference the two rasters through xDEM, which I already did.

Thanks.
Arindan

**Comment by rhugonnet** [comment]
Hi Arindan,
The first input parameter of `dDEM` is a `Raster` object, as you can find in the API documentation: https://xdem.readthedocs.io/en/latest/api.html#xdem.dDEM as well as the various examples.

Essentially you need to:
```python
import geoutils as gu
dh = gu.Raster('your_file.tif')
ddem = xdem.dDEM(dh, ...)
```
We already noted to better detail the link between xDEM and GeoUtils in the documentation. Additionally, the dDEM module is still in early development, we have many changes planned for the summer and beyond. Those should make things more flexible for inputs in the future. 
Hope xDEM is useful still :smile:

**Comment by arindan** [comment]
Hi Romain,

Thanks for the quick response. Yeah, I got it now.
Hope to see some more cool features/functions in xDEM in coming days.
Thanks.

Arindan

**Comment by rhugonnet** [comment]
> Hope to see some more cool features/functions in xDEM in coming days.

Coming **months**. I'm afraid that coding, documenting and testing a package is a slow endeavour :sweat_smile:
