### ISSUE TITLE
coregistration with ICESat-2 

### ISSUE THREAD

**Issue by mmazzolini** [GlacioHack/xdem#282]
Hi everyone, 

I am a PhD student at UiO and in our project, we hope to measure snow depth with ICESat-2 data and snow-free DEMs. In this context, coregistration is a crucial step. I know in the repository iamdonovan/pybob there is a similar functionality, but wanted to know if someone here is working on it. If not, I wonder if someone with some experience on the structure of xdem would like to collaborate on implementing this feature.

Cheers,
Marco.

**Comment by rhugonnet** [comment]
Hi Marco,

Great idea, and your timing is perfect! :smile: 
We intended to start further work on the `coreg.py` module end-of-summer.

I implemented support for point data last winter in a `coreg_point_support` branch that is on my fork (https://github.com/rhugonnet/xdem/tree/coreg_point_support). I also have a local script that retrieves ICESat-2 data using `icepyx`, post-processes it with `h5py`, and then runs the xDEM co-registration from the `coreg_point_support` branch.

It would be amazing to integrate this fully into xDEM, but there is still quite a bit of work on structuring, testing, plotting, and documenting! We should also coordinate with the developers of `icepyx` to avoid duplication (right now it downloads the data, but no post-processing. For this I adapted code from a script in https://github.com/ICESAT-2HackWeek/topohack/blob/master/topolib/gda_lib.py). There is also ICESat-2 SlideRule that is interesting to consider.

ICESat-2 aside, we had in mind to improve the structure, add plotting functionalities and write more tests for all `Coreg` classes soon. 
If you're up for it, I can invite you to our GlacioHack Slack channel (email me)

**Comment by mmazzolini** [comment]
Hi Romain,

what you're doing sounds exciting, especially creating a workflow for downloading snow-off ICESat-2 tracks and co-registers DEMs might be beneficial for many people given the consistency and accuracy of ICESat-2 data!

I am up for collaboration in general. Add me to the channel (my mail is mazzolini.marc@gmail.com). I participate in a summer school for some weeks, but I can join the effort from the second half of September!

**Comment by erikmannerfelt** [comment]
@mmazzolini, could we close this issue, as #346  is merged and we thus have (poorly refined but existing) functionality for Raster-point co-registration?

**Comment by rhugonnet** [comment]
We now have full point-raster support since #480, with the new documentation about to be published soon. Closing!
