### ISSUE TITLE
Rename the repository from DemUtils to xdem

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/xdem#29]
I think this is good to do as soon as possible, before this package becomes more popular. Running `pip install git+github.com/GlacioHack/DemUtils.git` only to `import xdem` doesn't make much sense!

**Comment by rhugonnet** [comment]
No PR open... and I haven't made a lot of changes locally. We could do it now, maybe?

**Comment by erikmannerfelt** [comment]
Yeah, go ahead from my part! I don't have the right to change its name. Maybe @adehecq  has it?

**Comment by rhugonnet** [comment]
Done! Strange that you can't, Amaury added you to the demutilsmaintainers with admin rights.

**Comment by adehecq** [comment]
> Done! Strange that you can't, Amaury added you to the demutilsmaintainers with admin rights.

Well, maintainers don't have exactly the same rights as admin. This is actually to prevent anyone to do a mess like this. Ideally there should be just one admin for each repo. I haven't had time to set the permissions for everyone actually.
