### ISSUE TITLE
Increase width of doc

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/xdem#295]
Currently, the width of the documentation is too narrow compared to our standard code width (120 characters). This means the code does not appear all at once and one needs to scroll horizontally.
There are some solutions [here](https://stackoverflow.com/questions/23211695/modifying-content-width-of-the-sphinx-theme-read-the-docs) that can be tested.
The comment by Yahya Yahyaoui seems the simplest, so worth testing.

**Comment by rhugonnet** [comment]
To leave a trace for later:
Tested the `html_theme_options = {'body_max_width': '70%'}`, does not work because we use the `html_theme = 'sphinx_rtd_theme'` theme.
We could only change the width, but also changing theme entirely!
