### ISSUE TITLE
Make xdem convertible to binder

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/xdem#296]
It would be great to create a binder from xdem repository directly. To do that, I see two issues:
1. Once the Binder created, starting a console and running `import xdem` raises "ModuleNotFoundError: No module named 'xdem'". Something must be changed to xdem's configuration probably
2. All our examples are python scripts, that are not so nice to work with on Jupyter Lab. If [jupytext](https://github.com/mwouts/jupytext/blob/main/README.md#sphinx-gallery-scripts) is added as a dependency, the jupyterlab will be able to open any script as a notebook. With jupytext, it works but the notebooks look quite ugly (see screenshot below), so we need to improve that.

![image](https://user-images.githubusercontent.com/3285905/188155228-000ec045-0f38-4374-a156-b0997acd48fe.png)

To reproduce:
1. Go https://mybinder.org/ and use URL GlacioHack/xdem to start the Binder.
2. Install jupytext with `conda install -c conda-forge jupytext`, then start `jupyter notebook` and open any of xdem's example scripts

**Comment by adehecq** [comment]
We don't have one 🙃 I thought all that was needed was the setup.py. 
I don't find any in OGGM. Do you have an example of a configuration somewhere? Because I tested running mybinder with OGGM/oggm and `import oggm` works...

**Comment by fmaussion** [comment]
> Because I tested running mybinder with OGGM/oggm and import oggm works...

No kidding... Times have changed! 

OK so OGGM uses quite a few shenanigans to share the same environment across many different binder links, which I don't recommend here. for other reps we usually have a binder folder like here: https://github.com/OGGM/glacier_simulator/tree/master/binder

**Comment by adehecq** [comment]
Adding the binder folder helps creating a new environment, but somehow opencv does not install correctly. I get the same error as [here](https://github.com/Fireline-Science/tello_sim/issues/10). I'll try the same fix.
