### ISSUE TITLE
DEM.to_vref fails if CRS does not have an EPSG code

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/xdem#313]
Due to [this line](https://github.com/GlacioHack/xdem/blob/main/xdem/dem.py#L161) that export self's CRS using the EPSG code, some functionalities do not work in case the CRS does not have an EPSG code, like `DEM.to_vref`.
To reproduce, need to create a custom CRS:
```
import xdem
import rasterio as rio

dem = xdem.DEM(xdem.examples.get_path("longyearbyen_ref_dem"))
dem.set_vref("EGM96")
dem.to_vref("WGS84")  # -> works fine

# Create DEM with custom CRS
dst_crs = rio.crs.CRS.from_proj4('+proj=aea +lat_0=75 +lon_0=15 +lat_1=70 +lat_2=80 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs=True')
dst_crs.to_epsg()  # -> None
dem_reproj = dem.reproject(dst_crs=dst_crs)
dem_reproj.set_vref("EGM96")
dem_reproj.to_vref("WGS84")  # -> raises Error below
```
raises 
> File ~/development/GlacioHack/xdem/xdem/dem.py:161, in DEM.ccrs(self)
> --> 161         self._ccrs = pyproj.Proj(init="EPSG:" + str(int(crs.to_epsg())), geoidgrids=self.vref_grid).crs
> TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

A first fix is to catch this error and add a NotImplementedError.

**Comment by rhugonnet** [comment]
Just popping quickly to say that this might be a duplicate of or related to #262, in case you decide to work on it shortly

**Comment by adehecq** [comment]
> Just popping quickly to say that this might be a duplicate of or related to #262, in case you decide to work on it shortly

Haha, I really have a short memory !! 😆 What's even funnier is that I wrote almost exactly the same MWE. I'll close this one then.

**Comment by adehecq** [comment]
Duplicate of https://github.com/GlacioHack/xdem/issues/262.
