### ISSUE TITLE
ValueError for xdem.coreg.BlockwiseCoreg()

### ISSUE THREAD

**Issue by xin1129** [GlacioHack/xdem#323]
There is a problem for me to use the Blockwise Coregistration. I divided  the raster using  _xdem.coreg.BlockwiseCoreg()_ first and then using _blockwise.fit()_

My codes are:

blockwise = xdem.coreg.BlockwiseCoreg(xdem.coreg.NuthKaab(), subdivision=64)

plt.title("Subdivision grid")
plt.imshow(blockwise.subdivide_array(dem_to_be_aligned.shape), cmap="gist_ncar")
plt.show()

blockwise.fit(reference_dem, dem_to_be_aligned, inlier_mask=inlier_mask)

The error is:
ValueError: Fitting failed for 19 chunks:
Less than 10 different cells exist.
Less than 10 different cells exist.
Less than 10 different cells exist.
Less than 10 different cells exist.
Less than 10 different cells exist.
and 14 more

I tried to change the number for subdivisions, like 32, 200, 50, etc. It still gives me the same error. I am not sure if it is because of too few pixels within some blocks. Could someone help me, please? Thank you!

**Comment by rhugonnet** [comment]
Hi @xin1129,

Thanks for reporting this issue. Can you provide us with a fully reproducible example, with either real or placeholder data (for example, you can copy the shape of your Raster and replace them by fixed values if the issue does not come from the values themselves).
 
Right now you provide exactly the same code as presented in [our gallery example](https://xdem.readthedocs.io/en/latest/advanced_examples/plot_blockwise_coreg.html#sphx-glr-advanced-examples-plot-blockwise-coreg-py), which is tested by our continuous integration workflow with our example data and works perfectly, so the issue has to come from the different data shape or content.

**Comment by xin1129** [comment]
[blockwise_test.zip](https://github.com/GlacioHack/xdem/files/9807711/blockwise_test.zip)
Hello,
Thank you very much for your prompt reply and your willingness to help! Attached are the data and the code.

**Comment by xin1129** [comment]
@rhugonnet Hello again,
Would that be because of the mask of stable landscapes is too small? When I run _blockwise.fit(reference_dem, dem_to_be_aligned, inlier_mask=inlier_mask)_ , would that be possible that some subdivided chunks have no stable landscapes? But it is just a guess, it could be something else. I look forward to your response.

**Comment by adehecq** [comment]
Hi @xin1129,
I had a quick look at your data, and it seems that most of your terrain is considered unstable, hence cannot be used for the coregistration. The blockwise coregistration requires enough stable terrain in any of the blocks to work, so if there is not enough stable terrain in some of the blocks, it raises the error you see.
It should work with a lower number of blocks, but for some reason, I still get an error even with as low as 4 blocks...
In any case, I would not recommend using the blockwise coregistration approach if you don't have enough stable terrain to constrain it.

**Comment by adehecq** [comment]
The figure below shows the elevation change (on the left) and the unstable mask (yellow is unstable). Is it correct? Can you include more stable terrain?

![Figure_1](https://user-images.githubusercontent.com/3285905/197168833-725ebbed-ddf9-4dd1-ad94-b26cc376aa4e.png)

**Comment by xin1129** [comment]
Hi @adehecq , I manually selected the stable landscape first by referring to the Google Earth Satellite image ( the current landscapes)  and historical aerial photos (dated back to 1950s, the old landscapes). I only selected those areas that I am sure they are stable by my visual inspection, and then reversed the selection and exported the unstable landscape shapefile as an unstable mask in order to fit the code as showed in the gallery example:

_glacier_outlines = gu.Vector(xdem.examples.get_path("longyearbyen_glacier_outlines"))
 # Create a stable ground mask (not glacierized) to mark "inlier data"
inlier_mask = ~glacier_outlines.create_mask(reference_dem)_

 Is there a way to directly deal with a stable mask, instead of inputting an unstable mask first and then converting it to a stable mask?

The figures you showed are correct. I would need to go back and include more stable terrain. I tried with 2 blocks, and it worked. It turned out only 2 blocks is working....It all makes sense now from your explanation!! Thank you so much for your help!
