### ISSUE TITLE
the datum shift bug of xDEM

### ISSUE THREAD

**Issue by liuh886** [GlacioHack/xdem#331]
Hi, I noticed a bug in the function dem.to_vref().

and have [a quick validation.](https://github.com/liuh886/etc/blob/main/xdem_to_crs.ipynb)

It shows the xDEM does not give the correct datum shift by using pyproj.

Please notice this if anyone uses .to_vref().

**Comment by rhugonnet** [comment]
Hi @liuh886,

Thanks for catching this! Especially with the `vref` features not being yet documented, you've been digging quite a bit into xDEM :wink:! Hope it is useful.

I will fix this bug and add tests to our CI in the next weeks to ensure that the vertical referencing is robust and consistent. Then we'll add some documentation on it in the next months.

**Comment by rhugonnet** [comment]
Ongoing, see https://github.com/GlacioHack/xdem/issues/344#issuecomment-1498306807 and #350 

Specifically, the axis swap was cause by the use of to the old PROJ syntax `+init`: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
