### ISSUE TITLE
Small text corrections

### ISSUE THREAD

**Issue by LucBeraud** [GlacioHack/xdem#338]
Hello,
Here is 3 small text mistakes I spotted:
- in the python doc of the function xdem.dem.DEM.reproject, the line ":param crs: Specifiy [...]" does not correspond to the argument name, which is "dst_crs".
- in the same doc, the "dst_bounds" argument descriptions says coordinates must be in the “source CRS" but it seems more it's the destination one, as the dst_bounds name also suggests it.
- A typing problem: for coregistration, the nuth_kaab.fit() verbose feature prints at one point "shit" instead of "shift".

**Comment by rhugonnet** [comment]
Love the last one :stuck_out_tongue:. Thanks for spotting this! 
Curious that `mypy` did not pick it up for the parameters syntax, that's supposedly checked, maybe we need to link it to GeoUtils somehow.

**Comment by rhugonnet** [comment]
1/ and 2/ are fixed in https://github.com/GlacioHack/geoutils/pull/351
3/ is fixed in https://github.com/GlacioHack/xdem/pull/340
