### ISSUE TITLE
NuthKaab fails without an error message when no data are available

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/xdem#343]
When a TBA raster is empty (or at least when `elevation_difference / slope` is only nan), `NuthKaab` fails with an empty AssertionError. It would be quite easy to fix this, as the error message should just be something along "input raster values do not overlap", or "at least one of the rasters are empty".
 
https://github.com/GlacioHack/xdem/blob/f40e897761704bffe5ad54ff6b43e3db0730a6f1/xdem/coreg.py#L95

**Comment by rhugonnet** [comment]
Fixed by #530, but leaving this open so that we add a test to check the error raised

**Comment by rhugonnet** [comment]
This is closed by https://github.com/GlacioHack/xdem/blob/22dbe7c6a3020a5f556065008862842463933a4c/tests/test_coreg/test_base.py#L541
