### ISSUE TITLE
Hide `latest` branch in public documentation, only show `stable` and previous releases

### ISSUE THREAD

**Issue by rhugonnet** [GlacioHack/xdem#361]
We should only have a public documentation for release versions, and start this absolutely before `v0.1` (and any more package advertisement).

**Comment by adehecq** [comment]
Or at least the default should not point to latest, but to the latest release. It's good for developers to have access to the latest documentation...

**Comment by rhugonnet** [comment]
To be able to do the above, @erikmannerfelt has to invite us to be maintainer on xDEM's readthedocs. And I just invited you on GeoUtils' readthedocs! :smile: 
Could also do the same for the Zenodo of xDEM, which hasn't been updated in a while. It's easier when we can relay each other.

**Comment by rhugonnet** [comment]
Update on this: the `stable` and `latest` versions of GeoUtils and xDEM's documentation are now rightly parameterized in readthedocs.

However, for this:
- I removed a wrong tag in GeoUtils that was making readthedocs point towards the wrong `stable`,
- xDEM's `stable` version fails during build because of the `htmlzip` typo #368,
- I will fix and merge https://github.com/GlacioHack/geoutils/pull/368, then rerelease so that the `stable` versions can build on both docs.

**Comment by rhugonnet** [comment]
All done, we can close!
