### ISSUE TITLE
Negative values predicted by `interp_nd_binning` problematic for error analysis

### ISSUE THREAD

**Issue by rhugonnet** [GlacioHack/xdem#380]
Opening after a discussion started by Enrico Mattea:

The linear extrapolation of `interp_nd_binning` can result in negative values (and, more generally, yield curious values) for points outside of the binning maximum bounds, especially as the "edge bins" tend to have less points to sample from, and thus more variability:
https://github.com/GlacioHack/xdem/blob/d91bf1cc9b3f36d77f3729649bc8e9edc6b42f9f/xdem/spatialstats.py#L342

It does happen that slope/curvature have very high values because of outliers, and those can be ignored during error prediction (`min_vals` argument of `interp_nd_binning`). 
If those outliers remain unfiltered in the dDEM, some of the predicted errors could then be negative? (untested)

So: should we rather default to nearest neighbour outside of the bin bounds, and leave the linear extrapolation option to the user?

**Comment by adehecq** [comment]
So `interp_nd_bininng` does linear extrapolation outside the bounds? I thought that it was doing nearest neighbor from looking at the docstring. 
"Fills the no-data present on the regular N-D binning grid with nearest neighbour from scipy.griddata, then provides an interpolant function that linearly interpolates/extrapolates using scipy.RegularGridInterpolator."
So in which case does it use the nearest neighbor and which case the RegularGridInterpolator?

I would indeed put NN as the default and linear extrapolation as an option. Alternatively, one could also include an option to set the bounds of the extrapolated values.

**Comment by rhugonnet** [comment]
The nearest neighbour was just to fill nodata values for points of the ND binning (not supported by interpolators). All other interpolation (between bins and outside bins) was linear.

I've fixed all and hopefully clarified the descriptions in #389
