### ISSUE TITLE
AttributeError: AxesImage.set() got an unexpected keyword argument 'cb_title'

### ISSUE THREAD

**Issue by xin1129** [GlacioHack/xdem#382]
Hello, I am testing the provided plot_nuth_kaab.py codes and got an error on this line:

ddem.show(cmap='coolwarm_r', vmin=-20, vmax=20, cb_title="Elevation change (m)")

The error message is:
ddem.show(cmap='coolwarm_r', vmin=-20, vmax=20, cb_title="Elevation change (m)")
Traceback (most recent call last):

  Cell In[58], line 1
    ddem.show(cmap='coolwarm_r', vmin=-20, vmax=20, cb_title="Elevation change (m)")

  File ~\Anaconda3\envs\xdem\Lib\site-packages\geoutils\raster\raster.py:2488 in show
    rshow(

  File ~\Anaconda3\envs\xdem\Lib\site-packages\rasterio\plot.py:160 in show
    ax.imshow(arr, **kwargs)

  File ~\Anaconda3\envs\xdem\Lib\site-packages\matplotlib\__init__.py:1442 in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)

  File ~\Anaconda3\envs\xdem\Lib\site-packages\matplotlib\axes\_axes.py:5658 in imshow
    im = mimage.AxesImage(self, cmap=cmap, norm=norm,

  File ~\Anaconda3\envs\xdem\Lib\site-packages\matplotlib\_api\deprecation.py:454 in wrapper
    return func(*args, **kwargs)

  File ~\Anaconda3\envs\xdem\Lib\site-packages\matplotlib\image.py:922 in __init__
    super().__init__(

  File ~\Anaconda3\envs\xdem\Lib\site-packages\matplotlib\image.py:274 in __init__
    self._internal_update(kwargs)

  File ~\Anaconda3\envs\xdem\Lib\site-packages\matplotlib\artist.py:1223 in _internal_update
    return self._update_props(

  File ~\Anaconda3\envs\xdem\Lib\site-packages\matplotlib\artist.py:1197 in _update_props
    raise AttributeError(

AttributeError: AxesImage.set() got an unexpected keyword argument 'cb_title'
________
I am new to coding and am not sure how to fix this issue. Could anyone help? Thanks in advanced.

**Comment by rhugonnet** [comment]
Hi @xin1129,
Looks like you're using an outdated version of the code. The new code uses `cbar_title` instead of `cb_title` for consistency with `matplotlib`.
See: https://github.com/GlacioHack/xdem/blob/main/examples/basic/plot_nuth_kaab.py#L30
You can close if that solves your issue! :slightly_smiling_face:

**Comment by xin1129** [comment]
Yes, it works! Thanks.

**Comment by xin1129** [comment]
Yes, it works! Thanks.
