### ISSUE TITLE
Add "equal count" hypsometric binning

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/xdem#39]
Right now, the hypsometric approach (PR #36) only allows for equally spaced bins. An alternative to equal spacing is having bins with equal pixel counts.

Correct me if I'm wrong, but the advantage would be on glaciers with a combination of flat and steep surfaces. If a nonlinear elevation vs. elevation change relationship is assumed, flat surfaces would be under-represented in bins with equal spacing. Bins with equal pixel counts, on the other hand, would make sure that each part of the glacier is represented better.

> Well, you can calculate a percentile bin, then use it in your percentile functions:
> `pbins = np.arange(min, max, bin_size)`
> `bins = np.percentile(mean_dem, pbins)`

_Originally posted by @adehecq in https://github.com/GlacioHack/xdem/pull/36#discussion_r591570480_

**Comment by rhugonnet** [comment]
This would probably also improve the filtering of outliers per bin (e.g., outside 5 NMAD) by ensuring the last bins in the accumulation areas are within a larger bin (few pixels are sampled at high elevations + effect of outliers in the reference DEM/wrong outlines).
For the record, this is how scikit-gstat is binning uniformly:
```python
return np.fromiter(
        (np.nanpercentile(d, (i / n) * 100) for i in range(1, n + 1)),
        dtype=float
    )
```
