### ISSUE TITLE
Numba deprecation warning

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/xdem#393]
With an update of numba (0.57.1 in my case), I now get a deprecation warning:

> NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit"

I guess the best is to set "nopython=True" and hope it works?

**Comment by adehecq** [comment]
Actually, many warnings come from skgstat...

**Comment by rhugonnet** [comment]
I'll try to look at those, I've been pushing changes there
