### ISSUE TITLE
Could `coreg/pipelines.py` get a different name?

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/xdem#405]
As you may notice, I'm only now starting to catch up with all of the changes that happened in the spring! I love the new structure in general but got very confused when looking for the `CoregPipeline` class, as my intuition led me to check the `pipelines.py` file.

I unfortunately don't have a great suggestion for what it could be called instead. Here are some random ideas:
- workflows
- default_workflow
- processing
- aio (all-in-one)
- fast (or a synonym, since it's made for quick-and-dirty-no-think co-registration)

I think "default_workflow" is the least worst suggestion in my opinion. What do you think, @adehecq , @rhugonnet ?

**Comment by erikmannerfelt** [comment]
I like `workflows.py` too! What do you think @adehecq ?

**Comment by adehecq** [comment]
Just reading this once the change has been implemented, but "workflows" is nice !
