### ISSUE TITLE
Make "Contributing" section more inviting

### ISSUE THREAD

**Issue by rhugonnet** [GlacioHack/xdem#414]
Add a "long" description to `CONTRIBUTING`, and list contributors in `README`? See original comment below.

For the "Contributing" file + README summary, I shortened it earlier this year to avoid repetition with other files (License, Install, etc) and keep it simple. But I now find it a bit "formal" (not too inviting)... What do you think?

I was thinking we could take some ideas from `pyproj`, which has a very inviting page (a bit too long to read to my taste, maybe we could mostly work on our intro, then keep our "Short" summary for experienced developers and add a "Long" one for new developers?): https://github.com/pyproj4/pyproj/blob/main/CONTRIBUTING.md
I also really like the effort to recognize contributors on the front page: https://github.com/pyproj4/pyproj#contributors-

_Originally posted by @rhugonnet in https://github.com/GlacioHack/xdem/issues/412#issuecomment-1686967693_

**Comment by adehecq** [comment]
I like the small icons for each contributor that really showcases the different ways one can contribute!
