### ISSUE TITLE
Start GitHub discussions for user questions

### ISSUE THREAD

**Issue by rhugonnet** [GlacioHack/xdem#420]
More and more questions are coming from users, often through the private way (email) and sometimes in issues.
I've been thinking that we could activate GitHub discussions in both GeoUtils and xDEM?

It works pretty nicely, it allows to:
- Link or transfer issues to discussion, and vice-versa,
- Mark questions as answered from a specific comment, so that people find information fast,
- Sort by themes/folders.
- And avoids having discussions posted in "Issues" (which I sometimes do...). 

Example in pyproj: https://github.com/pyproj4/pyproj/discussions.
We would need to clearly define what is posted in discussions, and what in issues, but I think that's pretty easy to determine:
- **Issue** = involves code development (bug, new feature, enhancement), 
- **Discussion** = involves an application (how to use, behaviour clarification, related projects and pipelines).

Thoughts @adehecq @erikmannerfelt?

**Comment by adehecq** [comment]
I think that's a good idea! Is there any limit from GitHub on the number of discussions etc?

**Comment by rhugonnet** [comment]
Done!
