### ISSUE TITLE
import error (Add warning on use of `pip` in README and documentation)

### ISSUE THREAD

**Issue by Xieleilab** [GlacioHack/xdem#421]
when i try to load the xdem package(0.0.13), the following error appear:
ImportError: cannot import name 'AnyNumber' from 'geoutils._typing' (d:\miniconda\envs\python_spatial\lib\site-packages\geoutils\_typing.py)

ther version of geoutils is 0.0.13

**Comment by rhugonnet** [comment]
Hi @Xieleilab,
xdem 0.0.13 has the following condition in its environment file: `geoutils==0.0.11`, so I'm not sure how you ended up with this environment. It will break with geoutils 0.0.13 except if you use the main branch on GitHub.

This should normally be solved automatically if you install it using conda/mamba as in the docs: https://xdem.readthedocs.io/en/stable/how_to_install.html.

**Comment by rhugonnet** [comment]
An addition: updating packages with `pip` typically breaks geospatial dependencies, so we don't recommend using it when updating a package linked to geospatial computations, including xDEM and GeoUtils.

Maybe we should add this in the documentation.

**Comment by rhugonnet** [comment]
Getting similar feedback from @vdevauxchupin on this: renaming issue to add a warning on the use of `pip` in README +  documentation.
