### ISSUE TITLE
`xdem.coreg.ICP` fails very underscriptively when not enough points are available

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/xdem#422]
I tried wrap my head around an error I got which even took me to the OpenCV C++ source code. Ooga booga!

When running `.fit_pts()` on a dataset that eventually didn't have enough points for registration (I'm still trying to figure out where the problem is; might be another issue coming up), ICP fails with a very strange error:
```
error: OpenCV(4.7.0) /build/source/modules/core/src/matrix.cpp:749: error: (-215:Assertion failed) m.dims >= 2 in function 'Mat'
```

Some debugging later and I realized one of the point clouds were empty, which the above error is **obviously** trying to tell me. 

There's already an exception handler (see below) for this but for some reason the exception is new. Easy fix is to just catch both exceptions and print the nicer error message.
https://github.com/GlacioHack/xdem/blob/3956073ef6c1846ffc6de3ac5368269f45131f42/xdem/coreg/affine.py#L543-L553

**Comment by rhugonnet** [comment]
The cause of this might have been SciPy map coordinates default prefilter removing data points: https://github.com/GlacioHack/geoutils/pull/484
