### ISSUE TITLE
Argument `subsample` does not work for a `CoregPipeline`

### ISSUE THREAD

**Issue by rhugonnet** [GlacioHack/xdem#428]
Could also solve #137 at the same time...

**Comment by rhugonnet** [comment]
Actually this is quite limiting because the old `Deramp` used to have an implicit `subsample` (of 500 000 samples) inside the class itself, and now this is not possible.

**Comment by adehecq** [comment]
Mmmh, difficult task !
Some thoughts regarding your suggestion:
- point 1: ok
- point 2: I don't understand why `_fit_func` cannot be used anymore...
- point 3: Ok for the mask. Or maybe list of indices to be used?
- point 4: could each subclass not just have a `subsampling` method that would be called during fit?

Something else I'm thinking. For some methods, it makes sense to randomly subsample the points (e.g. Tilt, Deramp, VerticalShift...), for others, it would make more sense to simply downgrade the resolution (e.g. NuthKaab). Maybe we could get away with two generic subsampling methods, one than randomly samples and one that downgrade?

**Comment by rhugonnet** [comment]
Yes, not easy!
Good points, some more thoughts:
- Point 2: It would be so that `fit()` can re-perform the subsampling (that can change for every method) + method attribution (P-P, R-P or R-R) consistently before sending to the `_fit_func`, without having to re-write that logic in every `_fit_func` (for subsampling) or `CoregPipeline` (for method attribution). Right now we call `apply()` in `CoregPipeline` for the same reason! This also answers Point 4 actually.
- Point 3: True, the vector is probably shorter in length, but then the integer data type likely makes it larger in memory than a full boolean array. Additionally, a list of indices would not be easily chunkable by Dask in relation to the DEMs, while we could derive a boolean mask in an out-of-memory way fairly easily...

Good point for the downsampling, actually I know a lot of users that ran into memory problems just because of that. There should be a logic in the pre-processing that always derives the fit from the lowest resolution data by default. I'll open an issue so we don't forget!
