### ISSUE TITLE
DEM should be possible to create from a Raster object

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/xdem#43]
I could submit a PR, but my aggressive formatting would mess up your code, @rhugonnet  ;)

If the user has a `Raster` and wants to convert this to a `DEM`, there is currently no easy way to do it. One hacky way is:
```python
dem = xdem.dem.DEM.from_array(raster.data, raster.transform, raster.crs, raster.nodata)
```
A quite simple conversion could be done in a `.from_raster()` static method. I recently learned this trick, and it's great because no copying is done in memory whatsoever!:
```python
class DEM(...):
    # all the old stuff
    def from_raster(raster: gu.georaster.Raster, vref_name=None, vref_grid=None, silent=False):
        dem = DEM.__new__(DEM)
        dem.__dict__ = raster.__dict__

        # user input
        dem.vref = vref_name
        dem.vref_grid = vref_grid
        dem.ccrs = None

        # trying to get vref from product name (priority to user input)
        # dem.__parse_vref_from_fn(silent=silent)
        return dem
```
This kind of works for me, but I just now realised that it won't work perfectly because it's supposed to be initialised through a `SatelliteImage`, so it doesn't have all the right attributes.

Anyway, this would be a really nice addition!

**Comment by rhugonnet** [comment]
Right now, I think this works:
```python
import geoutils as gu
import xdem
fn_img = xdem.examples.FILEPATHS["longyearbyen_ref_dem"]
r = gu.georaster.Raster(fn_img)
dem = xdem.dem.DEM(r.filename)
```
Which yields:
```
No metadata could be read from filename.
type(dem)
Out[7]: xdem.dem.DEM
```
It goes through the "init" again, but this is not an issue as those run instantly (manipulating strings). If we had to migrate some more problematic, larger objects, we'd have to use a specific function.
However we would have a problem if `self.filename` does not exist (a Raster copied in memory for instance). Then everything would fail. I guess it would be useful to store the original filename in `georaster.Raster`, maybe under `._filename`?

**Comment by erikmannerfelt** [comment]
> Right now, I think this works:
> 
> ```python
> import geoutils as gu
> import xdem
> fn_img = xdem.examples.FILEPATHS["longyearbyen_ref_dem"]
> r = gu.georaster.Raster(fn_img)
> dem = xdem.dem.DEM(r.filename)
> ```
> 
> Which yields:
> 
> ```
> No metadata could be read from filename.
> type(dem)
> Out[7]: xdem.dem.DEM
> ```
> 
> It goes through the "init" again, but this is not an issue as those run instantly (manipulating strings). If we had to migrate some more problematic, larger objects, we'd have to use a specific function.
> However we would have a problem if `self.filename` did not exist (a Raster copied in memory for instance). Then everything would fail. I guess it would be useful to store the original filename in `georaster.Raster`, maybe under `._filename`? Thoughts on this? @adehecq is getting better at understanding those underdash attributes :D

That only works assuming the Raster object has not been changed from disk:
```python
In [1]: import xdem

In [2]: import geoutils as gu

In [3]: raster = gu.georaster.Raster("examples/Longyearbyen/data/DEM_2009_ref.tif")

In [5]: raster_downsampled = raster.reproject(raster, dst_res=10)

In [6]: dem_downsampled = xdem.dem.DEM(raster_downsampled.filename)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-b3cc9f821625> in <module>
----> 1 dem_downsampled = xdem.dem.DEM(raster_downsampled.filename)

~/Projects/ETH/GlacioHack/xdem/xdem/dem.py in __init__(self, filename, vref_name, vref_grid, silent, **kwargs)
     59         """
     60 
---> 61         super().__init__(filename, **kwargs)
     62 
     63         if self.nbands > 1:

~/.local/share/conda/xdem/lib/python3.8/site-packages/geoutils/satimg.py in __init__(self, filename, attrs, load_data, bands, as_memfile, read_from_fn, datetime, tile_name, satellite, sensor, product, version, read_from_meta, fn_meta, silent)
    256         """
    257 
--> 258         super().__init__(filename, attrs=attrs, load_data=load_data, bands=bands, as_memfile=as_memfile)
    259 
    260         #TODO: maybe the Raster class should have an "original filename" attribute that doesn't get erased during

~/.local/share/conda/xdem/lib/python3.8/site-packages/geoutils/georaster.py in __init__(self, filename, bands, load_data, downsampl, masked, attrs, as_memfile)
     93         # Don't recognise the input, so stop here.
     94         else:
---> 95             raise ValueError('filename argument not recognised.')
     96 
     97         self._read_attrs(attrs)

ValueError: filename argument not recognised.

In [7]: raster_downsampled.filename
```
To make matters worse, it may sometimes work, but will give unexpected outcomes:
```python
In [16]: raster = gu.georaster.Raster("examples/Longyearbyen/data/DEM_2009_ref.tif")

In [17]: raster.data += 5

In [18]: dem = xdem.dem.DEM(raster.filename)
No metadata could be read from filename.

In [19]: assert np.mean(np.abs(raster.data - dem.data)) < 0.001
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-19-cd99e5be1816> in <module>
----> 1 assert np.mean(np.abs(raster.data - dem.data)) < 0.001

AssertionError:
```
The `.data` attribute of Raster can be modified while retaining the reference to the filename on disk. The `Raster.matches_disk` attribute is not even updated to be `False` (I'll submit an issue for this)!

I think the only reliable approach right now is my first hacky suggestion.

This problem will propagate to the `copy()` method in #46
