### ISSUE TITLE
Decide on author attribution across GeoUtils and xDEM

### ISSUE THREAD

**Issue by rhugonnet** [GlacioHack/xdem#431]
Right now we have:
- "The GlacioHack team" on PyPI: https://pypi.org/project/xdem/,
- "GlacioHack" in the LICENSE (which ships with Conda): https://github.com/GlacioHack/xdem/blob/main/LICENSE,
- "Erik Mannerfelt, Romain Hugonnet, Amaury Dehecq and others" in the docs: https://xdem.readthedocs.io/,
- "xDEM contributors" on Zenodo: https://zenodo.org/record/4809698.

It'd probably be better to be more consistent... What are your thoughts @adehecq @erikmannerfelt?

**Comment by adehecq** [comment]
Mmmh good point!
I think we should get away from "GlacioHack", which is now far behind us. Probably "xDEM contributors" is the most neutral.

**Comment by rhugonnet** [comment]
I agree that "xDEM contributors" (or "GeoUtils contributors") everywhere sounds good and is sustainable! 

Except maybe on the Zenodo DOI where we could have the listing of all contributors (something we can all use on our CVs, and that will update automatically with amount of contributions)? I think Zenodo can do that automatically.

What do you think @erikmannerfelt? Also, it's mid-September, we might be able to do #277! :stuck_out_tongue_winking_eye:
