### ISSUE TITLE
Coregistration: Tilt and VerticalShift pipelines in 0.0.16

### ISSUE THREAD

**Issue by MatteaE** [GlacioHack/xdem#447]
I've encountered a regression with coregistration between 0.0.13 and 0.0.16, affecting (at least) Tilt and VerticalShift when used in combination with NuthKaab.

Attached the relevant dh plots: coregistration result is wrong in 0.0.16 with any combination of NuthKaab + one of the two methods mentioned above; when used individually, NuthKaab and VerticalShift behave as expected also in 0.0.16. Also attached the input files to reproduce.

![demdiff_orig_plot](https://github.com/GlacioHack/xdem/assets/11635321/360e3272-7376-4f04-9541-380846b51c74)

[xdem_coreg_issue_data.zip](https://github.com/GlacioHack/xdem/files/13333797/xdem_coreg_issue_data.zip)

**Comment by rhugonnet** [comment]
Thanks a lot for the reproducible example @MatteaE!
Probably a bug introduced in https://github.com/GlacioHack/xdem/pull/436. Our tests for the coregistration are a bit old (2 years) and didn't catch this... It's one of our top priorities to update them. 
I'll look at this in details later this week :slightly_smiling_face:

**Comment by rhugonnet** [comment]
Found the bug, 4 letters were missing in a variable of `CoregPipeline.fit()`. Added tests in #450 so that won't happen again :smile:.
I'll release a `0.0.17` with the fix soon.

Thanks again @MatteaE!
