### ISSUE TITLE
Add a "Correct-your-DEM cheatsheet" page to the documentation?

### ISSUE THREAD

**Issue by rhugonnet** [GlacioHack/xdem#464]
Most interactions I have with users are about knowing the right tool to deal with their DEM issues, typically "here's this bias I have, what's the cause and how to correct it?".
The most common scenarios:
- Positive/Negative errors that look like the landforms = Horizontal coregistration,
- Big vertical error that is only positive or negative error, but not completely consistent everywhere = Vertical reference (geoid/ellipsoid),
- Patterns of errors after co-registration: What bias correction or other affine registration to use?
- Positive/negative errors around point samples: What method to use to compare point and raster data? (rasterizing points within pixels creates location biases, need to interpolate the raster at point locations).

We could have a "Cheatsheet" for users to look up if their scenario falls among the typical ones (with illustrated example), and point towards the right xDEM tools. :slightly_smiling_face:

**Comment by adehecq** [comment]
Great idea !
