### ISSUE TITLE
No module named geoutils.georaster

### ISSUE THREAD

**Issue by MightyFineMoraine** [GlacioHack/xdem#494]
when loading xdem into Jupyter, it cannot find the geoutils.georaster module. Geoutils version: 0.1.1.

![image](https://github.com/GlacioHack/xdem/assets/129288095/f103c39d-cd30-45e1-8f81-ef63d6b6a4d6)

**Comment by rhugonnet** [comment]
Hi @MightyFineMoraine,
Strange that you would have xDEM installed with a version of GeoUtils superior than `0.0.15`, the latest xDEM release (`0.0.18`) is forcing GeoUtils to `0.0.15` in dependencies: https://github.com/GlacioHack/xdem/blob/v0.0.18/dev-environment.yml#L18 (same in requirements.txt).

Maybe you did a developer install, or forced a version change through a forced pip install?
Can you try if normal install works for you?
https://xdem.readthedocs.io/en/stable/how_to_install.html#installing-with-mamba-recommended

**Comment by rhugonnet** [comment]
Also just checked xDEM's conda feedstock which is also rightfully forcing GeoUtils to `0.0.15` (https://github.com/conda-forge/xdem-feedstock/blob/main/recipe/meta.yaml#L42), with all tests passing. 
So normally classic install should work :wink:

**Comment by MightyFineMoraine** [comment]
I had installed them separately; uninstall and reinstall of only xdem sorted it. Thanks!

**Comment by rhugonnet** [comment]
Perfect! Closing this issue.

**Comment by jbbarre** [comment]
FYI, I did the same thing, i.e. installed geoutils and xdem separately, got the same problem and solved it with the same solution.

**Comment by rhugonnet** [comment]
@jbbarre Thanks for bringing this up, I wasn't expecting this to still be an issue in the latest releases. I'll look into it.

**Comment by rhugonnet** [comment]
Tested with both `conda` and `pip`: both direct xdem install, and geoutils then later xdem now work.
Might have been related to GeoPandas dropping Fiona as a fixed dependency (fixed a couple days ago #559), or a relic of our previous issues in older releases that are now fixed (in https://github.com/GlacioHack/xdem/pull/536 notably), and tested in CI to avoid running into these issues in the future!
