### ISSUE TITLE
area_or_point and get_mask - adapt changes to geouilts #519 and #501

### ISSUE THREAD

**Issue by liuh886** [GlacioHack/xdem#496]
Two bugs spotted with the latest updates of geoultils

#### Where
geoultis.raster line 1363
#### Reason

[raster.from_array has appended metadata `area_or_point`](https://github.com/GlacioHack/geoutils/pull/509), however, as the subclass, DEM has an override method from_array. When the self is a DEM instance, self.from_array do not accept argument `area_or_point` unless the override method accepts it as well.

#### Corrections
If a subclass overrides a method from its parent class, the overriding method should have the same signature (i.e., the same number and names of parameters) as the method in the parent class.  The same error has happened before #416 .

For the same reason, self.tags should be update as well.

#### File changes
DEM.from_array

#### Where
Volumne.py line 12
#### Reason
['get_mask' has been a new method under the Raster class. ](https://github.com/GlacioHack/geoutils/pull/501)
#### Corrections
Change get_mask into get_mask_from_array
#### File changes
volumn.py

**Comment by rhugonnet** [comment]
Fixed in #480, see https://github.com/GlacioHack/xdem/pull/497#issuecomment-2019296137
