### ISSUE TITLE
Add polynomial fit, sinusoidal fit, along/across-track sampling

### ISSUE THREAD

**Issue by rhugonnet** [GlacioHack/xdem#50]
We need:
- Sampling along across-track,
- Sampling along along-track,
- Polynomial fit based on minimized RMSE for multiple degrees,
- Sinusoidal fit based on priors and basin-hopping optimization

All available here:  https://github.com/luc-girod/MMASTER-workflows/blob/master/pymmaster/mmaster_tools.py

**Comment by erikmannerfelt** [comment]
Sounds like good inclusions! Should they be in `spatial_tools` or `spstats`?

I have used the `coreg.deramp_dem()` function for polynomial fitting. It's a bit hacky for now, but this works:

```python
arr = # whatever you have
flat_surface = np.zeros_like(arr) + np.nanmedian(arr)

# Try to fit the arr to a flat surface using a X degree polynomial
deramped_arr = xdem.coreg.deramp_dem(arr, flat_surface, mask=None, deramping_degree=3)
```
It uses `scipy.optimize.least_squares()` to estimate the polynomial, which I think minimises the MAE of the residuals.

We could just write a tiny wrapper function for the `deramp_dem()` to not duplicate code.

**Comment by erikmannerfelt** [comment]
@rhugonnet I started on a least-squares approximation of sinusoidal fitting, but that stuff was hard! Is it this function in pymmaster that does sinusoidal fitting?

https://github.com/luc-girod/MMASTER-workflows/blob/d837ddae3ebf37f3ed4dca109134b34d28f7e6a7/pymmaster/mmaster_tools.py#L764

**Comment by rhugonnet** [comment]
It's split between different subfunctions.
The core of it is `correct_along_track_bias`: we do sinusoidal fitting by defining priors and constraining the parameters through basin-hopping optimization: https://github.com/luc-girod/MMASTER-workflows/blob/d837ddae3ebf37f3ed4dca109134b34d28f7e6a7/pymmaster/mmaster_tools.py#L1066
Based on: https://doi.org/10.1021/jp970984n

**Comment by erikmannerfelt** [comment]
Oh boy, that's over my head. Maybe I could leave that to you?

**Comment by rhugonnet** [comment]
:+1:
