### ISSUE TITLE
Clarify which angle is needed for DirectionalBias

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/xdem#512]
The docstring at [this line](https://github.com/GlacioHack/xdem/blob/3b3e59c4e2fe83124fd1ba57e036c086065231de/xdem/coreg/biascorr.py#L732) is not clear enough. 
My understanding is that we need to provide the angle with reference to the x axis, in clockwise direction. That's what I inferred from looking at the results of [that line](https://github.com/GlacioHack/xdem/blob/3b3e59c4e2fe83124fd1ba57e036c086065231de/xdem/coreg/biascorr.py#L766) (clever way of not interpolating the data btw 😉), providing the wrong angle means one may look at across-track instead of along-track direction. 
Ii not clarified, I think it's more intuitive for most people to see it as the angle w.r.t. the y axis, because satellite images are typically only slightly rotated compared to that axis.

**Comment by rhugonnet** [comment]
Closed by #526
