### ISSUE TITLE
Collect references of projects using xdem

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/xdem#528]
Out of interest, for referencing in papers, and for some light boasting, it would be nice to have a list of papers using xdem in the documentation! A short non-comprehensive list is:

- https://doi.org/10.1016/j.rse.2022.113379
- https://doi.org/10.33799/jokull2023.73.035
- https://doi.org/10.5194/tc-17-3251-2023
- https://doi.org/10.5194/isprs-archives-XLVIII-4-W1-2022-5-2022
- https://doi.org/10.1109/JSTARS.2022.3188922
- https://doi.org/10.5194/tc-16-3249-2022
- https://doi.org/10.1016/j.qsa.2021.100041
- https://doi.org/10.1016/j.geomorph.2023.108805
- https://doi.org/10.1038/s41467-024-48886-x

MSc theses:
- https://doi.org/10.3929/ethz-b-000637956
- https://hdl.handle.net/11250/3057200
- http://hdl.handle.net/10852/103730

**Comment by rhugonnet** [comment]
Great idea! I will try to add this in #502 :slightly_smiling_face:
