### ISSUE TITLE
Add function to get a transformation matrix betwen two PCs

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/xdem#58]
For now, deramping and nuth_kaab algorithm do not return a transformation matrix. Returning a trasnformation matrix would make it easier to:
- chain with other approaches like ICP, by simply multiplying the two transformations
- update the associated cameras
- save the applied transformation and possibly apply it to other PC/DEMs

So far, the best solution I found is this library: https://github.com/jewettaij/superpose3d
There is a lot of unused code there, so it could be worth just rewriting some of the code.

**Comment by erikmannerfelt** [comment]
Oops, I kind of duplicated this suggestion in #67.

I suggest to keep them both, however, as this issue also touches on transforming external data such as camera positions, and my issue includes some pointers toward implementing it.

**Comment by erikmannerfelt** [comment]
This was implemented in #71 .
