### ISSUE TITLE
Several coreg functions do not work well with masked arrays

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/xdem#61]
Fixed for deramping in #60 
Need to be fixed for amaury_coregister_dem.

**Comment by erikmannerfelt** [comment]
I believe there are issues with the opencv approach as well, right? I'll get on it during the weekdays

**Comment by adehecq** [comment]
I think this is fixed in commit 1a59345. But this is worth discussing this at our next meeting. Many coreg functions were implemented before geoutils was really operational and are not compatible with geoutils Rasters.

**Comment by erikmannerfelt** [comment]
@adehecq that looks like a great addition, but I can't see it in `xdem/main`. Is this commit in your own fork?

**Comment by adehecq** [comment]
> @adehecq that looks like a great addition, but I can't see it in `xdem/main`. Is this commit in your own fork?

Yes, in my own fork. Unfortunately it was part of a larger PR that is still WIP.

**Comment by erikmannerfelt** [comment]
This is fixed, right?

**Comment by adehecq** [comment]
I believe so, but can you find the PR/commit that fixed it?

**Comment by erikmannerfelt** [comment]
With #71
