### ISSUE TITLE
Coreg functions modify the `to_be_aligned_dem` inplace

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/xdem#65]
Minimal example:
```python
import geoutils as gu
import xdem

ref = xdem.dem.DEM(xdem.examples.FILEPATHS["longyearbyen_ref_dem"])
tba = xdem.dem.DEM(xdem.examples.FILEPATHS["longyearbyen_tba_dem"])
glacier_outlines = gu.geovector.Vector(xdem.examples.FILEPATHS["longyearbyen_glacier_outlines"])

tba_original = tba.copy()

xdem.coreg.coregister(ref, tba, mask=glacier_outlines)

assert tba_original == tba  # Raises AssertionError
```
This will fail, because the `tba` will be masked with the `glacier_outlines`. This can obviously lead to some unexpected side-effects, but we should still discuss it before I do something about it:

If the DEMs in question are huge, I can't simply do `tba.copy()` inside the `coregister()` function due to memory limits. Maybe an optional keyword should exist, to choose between modifying inplace (default would be to copy) or not? What do you think, @rhugonnet and @adehecq?

**Comment by adehecq** [comment]
Something I wanted to discuss actually. In many coreg functions, the data is copied once or sometimes twice. For large arrays this will become an issue very quickly. So yes, we should make sure that we are clear on how the input data is treated, whether it's replaced or duplicated (preferably only once).

**Comment by erikmannerfelt** [comment]
I'm bringing up all of these issues so I can make sure that they are all fixed when we completely revise the `coreg.py` structure.

I like the idea of trying to copy only once at most in the functions. Right now, there's copy-mayhem (I focused on getting it to work rather than being efficient).

A related thought is how one would put these things in test form... Spawn the process in a separate thread and then continually measure `psutil.Process(os.getpid()).memory_info()[0]`? The command gets the KiB use of the current process, so one could make sure it doesn't consume more than e.g. twice its initial value. Any ideas on a simpler approach?

**Comment by adehecq** [comment]
I often use psutils too. But I think there might be better approaches to check the memory usage at each line, e.g. with a memory profiler like that one: https://pypi.org/project/memory-profiler/

**Comment by erikmannerfelt** [comment]
That's cool, thanks!
