### ISSUE TITLE
NMAD functions not working with masked_arrays

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/xdem#66]
First of all, there are two idential functions:
```python
xdem.coreg.calculate_nmad()
xdem.spatial_tools.nmad()
```
This is largely my fault, since I added my own in November when `spatial_tools` existed but wasn't in my field of vision.

Second, both trigger odd warnings when passing `masked_array`s to them:
```python
In [1]: import xdem

In [2]: import numpy

In [3]: masked = np.ma.masked_array([1, 2, 3, 3], mask=[True, True, False, False])

In [4]: equivalent_array = np.array([3, 3])

In [5]: masked.mean() == equivalent_array.mean()
Out [5]: True

In [6]: masked_nmad = xdem.spatial_tools.nmad(masked)
/home/erik/.local/share/conda/xdem/lib/python3.8/site-packages/numpy/core/fromnumeric.py:753: UserWarning: Warning: 'partition' will ignore the 'mask' of the MaskedArray.
  a.partition(kth, axis=axis, kind=kind, order=order)

In [7]: nmad = xdem.spatial_tools.nmad(equivalent_array)

In [8]: masked_nmad == nmad
Out [8]: False

In [9]: nmad
Out [9]: 0.0

In [10]: masked_nmad
Out [10]: 1.4826
```

For both `masked` and `equivalent_array`, I expected the NMAD to be 0. The output of the `masked_nmad` suggests to me that it just returns the `nfact` which is exactly `1.4826`.

I think the function has to check first if the array is a masked_array or not, then act accordingly.
Also, in the `coreg.py` revision (#24), I should remove the duplicated `calculate_nmad()`.

**Comment by rhugonnet** [comment]
If we keep masked_arrays everywhere, we'll probably need to implement similar stats function as here: https://github.com/dshean/pygeotools/blob/master/pygeotools/lib/malib.py#L1496
