### ISSUE TITLE
Convert coregistration results to 4x4 transformation matrices

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/xdem#67]
@adehecq and I have discussed at multiple points in time that this would be a nice addition. For example, if one would want to use the results of the coregistration in another tool (ASP / Metashape etc.), 4x4 transformation matrices are the way to go.

For bias corrections, it would be as simple as:
```python
[
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, bias],
    [0, 0, 0, 1]
]
```
for translations:
```python
[
    [1, 0, 0, xcorr],
    [0, 1, 0, ycorr],
    [0, 0, 1, bias],
    [0, 0, 0, 1]
]
```
We also discussed that 1st degree deramps can be described as a bias, rotation and scale in the horizontal direction. 2nd degree and higher deramps are however impossible to describe as a 4x4 matrix, and could return a `NotImplementedError` or similar.

PDAL and opencv already provide matrices from their ICP approaches, so this would be simple to return as a np.ndarray.

This could be part of the `coreg.py` revision initiative (#24).

**Comment by rhugonnet** [comment]
:+1:
