### ISSUE TITLE
Add `.error()` method or similar to `Coreg` class

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/xdem#76]
There should be a quick way to figure out how well the coregistration went. NMAD is one alternative, but it could hide potential biases. I like RMSE's, but they often look dauntingly big!

The `.error()` (or similar) method could alternatively take an argument to choose (`metric="nmad"`).

Opinions?

**Comment by adehecq** [comment]
Maybe we should have a method .residuals() that returns the residuals and then one can run whatever calculation one wants on them?
