### ISSUE TITLE
Allow filters in a `CoregPipeline`

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/xdem#77]
Copying the code suggested by @rhugonnet, this (or something very similar) should be possible:
```python
step1 = filters.NMAD()
step2 = coreg.BiasCorr()
step3. = filters.MedianKernel()
step4 = coreg.ICP()
step5 = biascorr.AlongTrack()

pipeline = step1 + step2 + step3 + step4 + step5
```

It either suggests a more general `Pipeline` class, or just that the (not yet implemented) `Filter`  class just assumes it will be used in a `CoregPipeline` when calling `Filter.__add__()`

**Comment by rhugonnet** [comment]
The new structure implemented in #158 will allow filters (just need to implement them now!)
