### ISSUE TITLE
Move `coreg.BiasCorr` and `coreg.Deramp` to `biascorr.py`?

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/xdem#78]
To better fit the names of the script files, these may fit better in `biascorr.py`. 

I strongly suggest that they still inherit from the `Coreg` class, however, to be fully compatible with each other. I suggest the same for e.g. `biascorr.AlongTrack()`.

**Comment by rhugonnet** [comment]
Fixed by #158
